Change empty values to display null instead of dash string
aguilarguisado/JSONFace pull request #5
Opened 2024-05-20 13:43 UTC by krokiet

Hi again!

I have a small PR this time that changes "--" for empty values to null value. I think that this fits json format better as values can be null while "--" mean a totaly different value type from the one used when there is a value to be displayed. For example hear rate is a number but when the value is no longer present it changes to string.

Feel free to reject this PR if you don't agree and/or change null value color.

Right now this mainly applies to hr but I intend to add more features and then null will be displayed more often (for example for bodyBattery and hr when you take off the watch or for temperature when there is no phone to sync data for a longer time).

![obraz](https://github.com/aguilarguisado/JSONFace/assets/9075889/75dcbcf6-96be-4b5c-bf49-bae36c6287c0)

2024-05-20 14:18 UTC, aguilarguisado commented
Hi @krokiet ! This sound wonderful. I thought "--" more user friendly but I agree with you due to the type of users of the face.

I have seen different themes in VS and all of them use the same color for numbers and nulls.
![image](https://github.com/aguilarguisado/JSONFace/assets/3255055/f03ca8e9-e5ff-47e8-b762-7df98dbedd61)

Not the same for booleans. This specific theme uses the same color also for booleans but default VSCode does not. There is not any boolean field yet so it can be decided later.

Do you mind just address the color change? I will merge and upload the new version to connect-IQ.

2024-05-20 14:20 UTC, aguilarguisado requested changes
Looks pretty good. Just color adjustment.

2024-05-20 14:20 UTC, aguilarguisado commented on source/JSONFaceView.mc
> +        dc.setColor(COLOR_PURPLE_NULL, Graphics.COLOR_TRANSPARENT);
just use the same orange color than it is used for numbers

2024-05-23 10:19 UTC, merged

2024-05-23 10:20 UTC, aguilarguisado commented
This commits were added in #6

2024-05-25 08:01 UTC, krokiet commented
Hi @aguilarguisado 
Sorry for the late reply but I had a bit bussy time.

I agree with your comments and thanks for merging.
Now that there is a configuration implemented it will be possible to also implement picking a color for each type in config or selecting entire color schemes. But this is something for the future.

I will start working on adding some features and create a PR once done/partially done to get your feedback.